package org.fagu.fmv.ffmpeg.utils.srcgen;

import java.util.List;

import org.fagu.fmv.ffmpeg.coder.Encoders;
import org.fagu.fmv.ffmpeg.coder.Encoders.EncoderHelp;
import org.fagu.fmv.ffmpeg.soft.FFMpeg;
import org.fagu.fmv.ffmpeg.utils.HelpCache;


/**
 * @author f.agu
 */
public class GenerateEncoders {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		System.out.println("// Generated by " + GenerateEncoders.class.getName());
		System.out.println("// with " + FFMpeg.search().getFirstFound().getSoftInfo().toString());
		System.out.println();

		HelpCache<Encoders, EncoderHelp> helpCache = Encoders.getHelpCache();
		for(String name : helpCache.availableNames()) {
			List<EncoderHelp> helps = helpCache.cache(name);
			if(helps.isEmpty()) {
				continue;
			}
			if(helps.size() > 1) {
				throw new RuntimeException("Duplicate name: " + name + " => " + helps);
			}
			String comment = helps.get(0).getText();
			System.out.println("// " + comment);
			String fieldName = ClassNameUtils.fieldStatic(name);
			StringBuilder sb = new StringBuilder(50);
			sb.append("public static final Encoders ").append(fieldName).append(" = new Encoders(\"").append(name).append('"');
			if(comment.contains("image")) {
				sb.append(", SubType.IMAGE");
			}
			sb.append(");");
			System.out.println(sb);
		}
	}

}
