package org.fagu.fmv.ffmpeg.soft;

/*-
 * #%L
 * fmv-ffmpeg
 * %%
 * Copyright (C) 2014 - 2017 fagu
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 * #L%
 */
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.Map.Entry;
import java.util.NavigableMap;
import java.util.TreeMap;

import org.fagu.version.Version;


/**
 * @author f.agu
 * @created 24 janv. 2017 12:25:47
 */
public class BuildMapping {

	private static final NavigableMap<Version, LocalDate> VERSION_DATE_MAP = versionDateMap();

	private static final NavigableMap<Integer, LocalDate> BUILD_DATE_MAP = buildDateMap();

	/**
	 * 
	 */
	private BuildMapping() {}

	/**
	 * @param version
	 * @return
	 */
	public static LocalDate versionToLocalDate(Version version) {
		Entry<Version, LocalDate> lowerEntry = VERSION_DATE_MAP.lowerEntry(version);
		if(lowerEntry == null) {
			return VERSION_DATE_MAP.firstEntry().getValue();
		}
		return lowerEntry.getValue();
	}

	/**
	 * @param version
	 * @return
	 */
	public static Date versionToDate(Version version) {
		return Date.from(versionToLocalDate(version).atStartOfDay(ZoneId.systemDefault()).toInstant());
	}

	/**
	 * @param build
	 * @return
	 */
	public static LocalDate buildToLocalDate(int build) {
		LocalDate localDate = BUILD_DATE_MAP.get(build);
		if(localDate != null) {
			return localDate;
		}
		Entry<Integer, LocalDate> lowerEntry = BUILD_DATE_MAP.lowerEntry(build);
		if(lowerEntry == null) {
			return BUILD_DATE_MAP.firstEntry().getValue();
		}
		return lowerEntry.getValue();
	}

	/**
	 * @param build
	 * @return
	 */
	public static Date buildToDate(int build) {
		return Date.from(buildToLocalDate(build).atStartOfDay(ZoneId.systemDefault()).toInstant());
	}

	// *************************************************

	/**
	 * @return
	 */
	private static NavigableMap<Version, LocalDate> versionDateMap() {
		// Generated by org.fagu.fmv.ffmpeg.soft.BuildMappingGenerator
		// from http://ffmpeg.org/releases/

		NavigableMap<Version, LocalDate> map = new TreeMap<>();
		// ==== 4.x.x
		map.put(new Version(4, 2, 1), LocalDate.of(2019, 9, 7));
		map.put(new Version(4, 2), LocalDate.of(2019, 8, 6));
		map.put(new Version(4, 1, 4), LocalDate.of(2019, 7, 8));
		map.put(new Version(4, 1, 3), LocalDate.of(2019, 4, 1));
		map.put(new Version(4, 1, 2), LocalDate.of(2019, 3, 23));
		map.put(new Version(4, 1, 1), LocalDate.of(2019, 2, 9));
		map.put(new Version(4, 1), LocalDate.of(2018, 11, 6));
		map.put(new Version(4, 0, 4), LocalDate.of(2019, 3, 28));
		map.put(new Version(4, 0, 3), LocalDate.of(2018, 11, 3));
		map.put(new Version(4, 0, 2), LocalDate.of(2018, 7, 18));
		map.put(new Version(4, 0, 1), LocalDate.of(2018, 6, 16));
		map.put(new Version(4, 0), LocalDate.of(2018, 4, 20));
		// ==== 3.x.x
		map.put(new Version(3, 4, 6), LocalDate.of(2019, 3, 29));
		map.put(new Version(3, 4, 5), LocalDate.of(2018, 11, 1));
		map.put(new Version(3, 4, 4), LocalDate.of(2018, 7, 18));
		map.put(new Version(3, 4, 3), LocalDate.of(2018, 7, 8));
		map.put(new Version(3, 4, 2), LocalDate.of(2018, 2, 12));
		map.put(new Version(3, 4, 1), LocalDate.of(2017, 12, 11));
		map.put(new Version(3, 4), LocalDate.of(2017, 10, 15));
		map.put(new Version(3, 3, 9), LocalDate.of(2018, 11, 18));
		map.put(new Version(3, 3, 8), LocalDate.of(2018, 7, 17));
		map.put(new Version(3, 3, 7), LocalDate.of(2018, 4, 14));
		map.put(new Version(3, 3, 6), LocalDate.of(2018, 1, 1));
		map.put(new Version(3, 3, 5), LocalDate.of(2017, 10, 26));
		map.put(new Version(3, 3, 4), LocalDate.of(2017, 9, 12));
		map.put(new Version(3, 3, 3), LocalDate.of(2017, 7, 29));
		map.put(new Version(3, 3, 2), LocalDate.of(2017, 6, 7));
		map.put(new Version(3, 3, 1), LocalDate.of(2017, 5, 15));
		map.put(new Version(3, 3), LocalDate.of(2017, 4, 13));
		map.put(new Version(3, 2, 14), LocalDate.of(2019, 5, 14));
		map.put(new Version(3, 2, 13), LocalDate.of(2019, 1, 15));
		map.put(new Version(3, 2, 12), LocalDate.of(2018, 7, 19));
		map.put(new Version(3, 2, 11), LocalDate.of(2018, 7, 9));
		map.put(new Version(3, 2, 10), LocalDate.of(2018, 1, 13));
		map.put(new Version(3, 2, 9), LocalDate.of(2017, 10, 27));
		map.put(new Version(3, 2, 8), LocalDate.of(2017, 9, 17));
		map.put(new Version(3, 2, 7), LocalDate.of(2017, 7, 30));
		map.put(new Version(3, 2, 6), LocalDate.of(2017, 6, 18));
		map.put(new Version(3, 2, 5), LocalDate.of(2017, 5, 16));
		map.put(new Version(3, 2, 4), LocalDate.of(2017, 2, 10));
		map.put(new Version(3, 2, 3), LocalDate.of(2017, 2, 6));
		map.put(new Version(3, 2, 2), LocalDate.of(2016, 12, 6));
		map.put(new Version(3, 2, 1), LocalDate.of(2016, 11, 26));
		map.put(new Version(3, 2), LocalDate.of(2016, 10, 27));
		map.put(new Version(3, 1, 11), LocalDate.of(2017, 9, 25));
		map.put(new Version(3, 1, 10), LocalDate.of(2017, 8, 4));
		map.put(new Version(3, 1, 9), LocalDate.of(2017, 6, 22));
		map.put(new Version(3, 1, 8), LocalDate.of(2017, 5, 17));
		map.put(new Version(3, 1, 7), LocalDate.of(2017, 2, 9));
		map.put(new Version(3, 1, 6), LocalDate.of(2016, 12, 6));
		map.put(new Version(3, 1, 5), LocalDate.of(2016, 10, 22));
		map.put(new Version(3, 1, 4), LocalDate.of(2016, 10, 1));
		map.put(new Version(3, 1, 3), LocalDate.of(2016, 8, 26));
		map.put(new Version(3, 1, 2), LocalDate.of(2016, 8, 9));
		map.put(new Version(3, 1, 1), LocalDate.of(2016, 7, 1));
		map.put(new Version(3, 1), LocalDate.of(2016, 6, 27));
		map.put(new Version(3, 0, 12), LocalDate.of(2018, 10, 28));
		map.put(new Version(3, 0, 11), LocalDate.of(2018, 2, 28));
		map.put(new Version(3, 0, 10), LocalDate.of(2017, 12, 2));
		map.put(new Version(3, 0, 9), LocalDate.of(2017, 7, 19));
		map.put(new Version(3, 0, 8), LocalDate.of(2017, 5, 18));
		map.put(new Version(3, 0, 7), LocalDate.of(2017, 2, 11));
		map.put(new Version(3, 0, 6), LocalDate.of(2017, 2, 5));
		map.put(new Version(3, 0, 5), LocalDate.of(2016, 12, 6));
		map.put(new Version(3, 0, 4), LocalDate.of(2016, 10, 19));
		map.put(new Version(3, 0, 3), LocalDate.of(2016, 9, 5));
		map.put(new Version(3, 0, 2), LocalDate.of(2016, 4, 28));
		map.put(new Version(3, 0, 1), LocalDate.of(2016, 3, 29));
		map.put(new Version(3, 0), LocalDate.of(2016, 2, 15));
		// ==== 2.x.x
		map.put(new Version(2, 8, 15), LocalDate.of(2018, 7, 16));
		map.put(new Version(2, 8, 14), LocalDate.of(2018, 2, 19));
		map.put(new Version(2, 8, 13), LocalDate.of(2017, 9, 2));
		map.put(new Version(2, 8, 12), LocalDate.of(2017, 6, 6));
		map.put(new Version(2, 8, 11), LocalDate.of(2017, 2, 9));
		map.put(new Version(2, 8, 10), LocalDate.of(2016, 12, 6));
		map.put(new Version(2, 8, 9), LocalDate.of(2016, 12, 4));
		map.put(new Version(2, 8, 8), LocalDate.of(2016, 9, 19));
		map.put(new Version(2, 8, 7), LocalDate.of(2016, 4, 29));
		map.put(new Version(2, 8, 6), LocalDate.of(2016, 2, 1));
		map.put(new Version(2, 8, 5), LocalDate.of(2016, 1, 15));
		map.put(new Version(2, 8, 4), LocalDate.of(2015, 12, 20));
		map.put(new Version(2, 8, 3), LocalDate.of(2015, 11, 27));
		map.put(new Version(2, 8, 2), LocalDate.of(2015, 11, 12));
		map.put(new Version(2, 8, 1), LocalDate.of(2015, 10, 14));
		map.put(new Version(2, 8), LocalDate.of(2015, 9, 9));
		map.put(new Version(2, 7, 7), LocalDate.of(2016, 4, 30));
		map.put(new Version(2, 7, 6), LocalDate.of(2016, 2, 1));
		map.put(new Version(2, 7, 5), LocalDate.of(2016, 1, 15));
		map.put(new Version(2, 7, 4), LocalDate.of(2015, 12, 21));
		map.put(new Version(2, 7, 3), LocalDate.of(2015, 11, 19));
		map.put(new Version(2, 7, 2), LocalDate.of(2015, 7, 20));
		map.put(new Version(2, 7, 1), LocalDate.of(2015, 6, 19));
		map.put(new Version(2, 7), LocalDate.of(2015, 6, 10));
		map.put(new Version(2, 6, 9), LocalDate.of(2016, 5, 3));
		map.put(new Version(2, 6, 8), LocalDate.of(2016, 2, 1));
		map.put(new Version(2, 6, 7), LocalDate.of(2016, 1, 15));
		map.put(new Version(2, 6, 6), LocalDate.of(2015, 12, 22));
		map.put(new Version(2, 6, 5), LocalDate.of(2015, 11, 23));
		map.put(new Version(2, 6, 4), LocalDate.of(2015, 7, 25));
		map.put(new Version(2, 6, 3), LocalDate.of(2015, 6, 4));
		map.put(new Version(2, 6, 2), LocalDate.of(2015, 4, 12));
		map.put(new Version(2, 6, 1), LocalDate.of(2015, 3, 16));
		map.put(new Version(2, 6), LocalDate.of(2015, 3, 7));
		map.put(new Version(2, 5, 11), LocalDate.of(2016, 2, 3));
		map.put(new Version(2, 5, 10), LocalDate.of(2016, 1, 16));
		map.put(new Version(2, 5, 9), LocalDate.of(2015, 12, 7));
		map.put(new Version(2, 5, 8), LocalDate.of(2015, 7, 31));
		map.put(new Version(2, 5, 7), LocalDate.of(2015, 6, 4));
		map.put(new Version(2, 5, 6), LocalDate.of(2015, 4, 19));
		map.put(new Version(2, 5, 5), LocalDate.of(2015, 3, 22));
		map.put(new Version(2, 5, 4), LocalDate.of(2015, 2, 13));
		map.put(new Version(2, 5, 3), LocalDate.of(2015, 1, 10));
		map.put(new Version(2, 5, 2), LocalDate.of(2014, 12, 23));
		map.put(new Version(2, 5, 1), LocalDate.of(2014, 12, 16));
		map.put(new Version(2, 5), LocalDate.of(2014, 12, 4));
		map.put(new Version(2, 4, 14), LocalDate.of(2017, 12, 31));
		map.put(new Version(2, 4, 13), LocalDate.of(2016, 2, 2));
		map.put(new Version(2, 4, 12), LocalDate.of(2015, 12, 10));
		map.put(new Version(2, 4, 11), LocalDate.of(2015, 8, 25));
		map.put(new Version(2, 4, 10), LocalDate.of(2015, 6, 4));
		map.put(new Version(2, 4, 9), LocalDate.of(2015, 4, 26));
		map.put(new Version(2, 4, 8), LocalDate.of(2015, 3, 30));
		map.put(new Version(2, 4, 7), LocalDate.of(2015, 2, 15));
		map.put(new Version(2, 4, 6), LocalDate.of(2015, 1, 13));
		map.put(new Version(2, 4, 5), LocalDate.of(2014, 12, 20));
		map.put(new Version(2, 4, 4), LocalDate.of(2014, 12, 1));
		map.put(new Version(2, 4, 3), LocalDate.of(2014, 11, 2));
		map.put(new Version(2, 4, 2), LocalDate.of(2014, 10, 5));
		map.put(new Version(2, 4, 1), LocalDate.of(2014, 9, 22));
		map.put(new Version(2, 4), LocalDate.of(2014, 9, 14));
		map.put(new Version(2, 3, 6), LocalDate.of(2015, 1, 6));
		map.put(new Version(2, 3, 5), LocalDate.of(2014, 11, 1));
		map.put(new Version(2, 3, 4), LocalDate.of(2014, 10, 3));
		map.put(new Version(2, 3, 3), LocalDate.of(2014, 8, 17));
		map.put(new Version(2, 3, 2), LocalDate.of(2014, 8, 11));
		map.put(new Version(2, 3, 1), LocalDate.of(2014, 7, 31));
		map.put(new Version(2, 3), LocalDate.of(2014, 7, 16));
		map.put(new Version(2, 2, 16), LocalDate.of(2015, 6, 18));
		map.put(new Version(2, 2, 15), LocalDate.of(2015, 4, 17));
		map.put(new Version(2, 2, 14), LocalDate.of(2015, 3, 15));
		map.put(new Version(2, 2, 13), LocalDate.of(2015, 2, 19));
		map.put(new Version(2, 2, 12), LocalDate.of(2015, 1, 20));
		map.put(new Version(2, 2, 11), LocalDate.of(2014, 12, 9));
		map.put(new Version(2, 2, 10), LocalDate.of(2014, 11, 1));
		map.put(new Version(2, 2, 9), LocalDate.of(2014, 10, 6));
		map.put(new Version(2, 2, 8), LocalDate.of(2014, 9, 21));
		map.put(new Version(2, 2, 7), LocalDate.of(2014, 8, 12));
		map.put(new Version(2, 2, 6), LocalDate.of(2014, 8, 6));
		map.put(new Version(2, 2, 5), LocalDate.of(2014, 7, 15));
		map.put(new Version(2, 2, 4), LocalDate.of(2014, 6, 23));
		map.put(new Version(2, 2, 3), LocalDate.of(2014, 6, 3));
		map.put(new Version(2, 2, 2), LocalDate.of(2014, 5, 5));
		map.put(new Version(2, 2, 1), LocalDate.of(2014, 4, 10));
		map.put(new Version(2, 2), LocalDate.of(2014, 3, 24));
		map.put(new Version(2, 1, 8), LocalDate.of(2015, 6, 4));
		map.put(new Version(2, 1, 7), LocalDate.of(2014, 12, 31));
		map.put(new Version(2, 1, 6), LocalDate.of(2014, 11, 28));
		map.put(new Version(2, 1, 5), LocalDate.of(2014, 6, 23));
		map.put(new Version(2, 1, 4), LocalDate.of(2014, 2, 24));
		map.put(new Version(2, 1, 3), LocalDate.of(2014, 1, 15));
		map.put(new Version(2, 1, 2), LocalDate.of(2014, 1, 13));
		map.put(new Version(2, 1, 1), LocalDate.of(2013, 11, 20));
		map.put(new Version(2, 1), LocalDate.of(2013, 10, 28));
		map.put(new Version(2, 0, 7), LocalDate.of(2015, 6, 10));
		map.put(new Version(2, 0, 6), LocalDate.of(2014, 11, 14));
		map.put(new Version(2, 0, 5), LocalDate.of(2014, 6, 25));
		map.put(new Version(2, 0, 4), LocalDate.of(2014, 3, 4));
		map.put(new Version(2, 0, 3), LocalDate.of(2013, 12, 24));
		map.put(new Version(2, 0, 2), LocalDate.of(2013, 10, 8));
		map.put(new Version(2, 0, 1), LocalDate.of(2013, 8, 11));
		map.put(new Version(2, 0), LocalDate.of(2013, 7, 10));
		// ==== 1.x.x
		map.put(new Version(1, 2, 12), LocalDate.of(2015, 2, 12));
		map.put(new Version(1, 2, 11), LocalDate.of(2014, 12, 19));
		map.put(new Version(1, 2, 10), LocalDate.of(2014, 11, 3));
		map.put(new Version(1, 2, 9), LocalDate.of(2014, 10, 7));
		map.put(new Version(1, 2, 8), LocalDate.of(2014, 8, 19));
		map.put(new Version(1, 2, 7), LocalDate.of(2014, 6, 23));
		map.put(new Version(1, 2, 6), LocalDate.of(2014, 3, 5));
		map.put(new Version(1, 2, 5), LocalDate.of(2014, 1, 16));
		map.put(new Version(1, 2, 4), LocalDate.of(2013, 10, 3));
		map.put(new Version(1, 2, 3), LocalDate.of(2013, 8, 27));
		map.put(new Version(1, 2, 2), LocalDate.of(2013, 7, 28));
		map.put(new Version(1, 2, 1), LocalDate.of(2013, 5, 10));
		map.put(new Version(1, 2), LocalDate.of(2013, 3, 15));
		map.put(new Version(1, 1, 16), LocalDate.of(2015, 3, 13));
		map.put(new Version(1, 1, 15), LocalDate.of(2014, 12, 21));
		map.put(new Version(1, 1, 14), LocalDate.of(2014, 8, 31));
		map.put(new Version(1, 1, 13), LocalDate.of(2014, 8, 9));
		map.put(new Version(1, 1, 12), LocalDate.of(2014, 6, 26));
		map.put(new Version(1, 1, 11), LocalDate.of(2014, 5, 11));
		map.put(new Version(1, 1, 10), LocalDate.of(2014, 4, 22));
		map.put(new Version(1, 1, 9), LocalDate.of(2014, 3, 7));
		map.put(new Version(1, 1, 8), LocalDate.of(2014, 1, 13));
		map.put(new Version(1, 1, 7), LocalDate.of(2013, 10, 11));
		map.put(new Version(1, 1, 6), LocalDate.of(2013, 8, 31));
		map.put(new Version(1, 1, 5), LocalDate.of(2013, 5, 13));
		map.put(new Version(1, 1, 4), LocalDate.of(2013, 3, 18));
		map.put(new Version(1, 1, 3), LocalDate.of(2013, 2, 23));
		map.put(new Version(1, 1, 2), LocalDate.of(2013, 2, 6));
		map.put(new Version(1, 1, 1), LocalDate.of(2013, 1, 20));
		map.put(new Version(1, 1), LocalDate.of(2013, 1, 7));
		map.put(new Version(1, 0, 10), LocalDate.of(2014, 7, 20));
		map.put(new Version(1, 0, 9), LocalDate.of(2014, 3, 10));
		map.put(new Version(1, 0, 8), LocalDate.of(2013, 9, 6));
		map.put(new Version(1, 0, 7), LocalDate.of(2013, 5, 14));
		map.put(new Version(1, 0, 6), LocalDate.of(2013, 3, 21));
		map.put(new Version(1, 0, 5), LocalDate.of(2013, 3, 4));
		map.put(new Version(1, 0, 4), LocalDate.of(2013, 2, 7));
		map.put(new Version(1, 0, 3), LocalDate.of(2013, 1, 22));
		map.put(new Version(1, 0, 2), LocalDate.of(2013, 1, 21));
		map.put(new Version(1, 0, 1), LocalDate.of(2012, 12, 3));
		map.put(new Version(1, 0), LocalDate.of(2012, 9, 28));
		// ==== 0.x.x
		map.put(new Version(0, 11, 5), LocalDate.of(2014, 3, 10));
		map.put(new Version(0, 11, 4), LocalDate.of(2013, 8, 28));
		map.put(new Version(0, 11, 3), LocalDate.of(2013, 3, 22));
		map.put(new Version(0, 11, 2), LocalDate.of(2012, 9, 19));
		map.put(new Version(0, 11, 1), LocalDate.of(2012, 6, 8));
		map.put(new Version(0, 11), LocalDate.of(2012, 5, 25));
		map.put(new Version(0, 10, 16), LocalDate.of(2015, 3, 12));
		map.put(new Version(0, 10, 15), LocalDate.of(2014, 8, 13));
		map.put(new Version(0, 10, 14), LocalDate.of(2014, 6, 29));
		map.put(new Version(0, 10, 13), LocalDate.of(2014, 6, 9));
		map.put(new Version(0, 10, 12), LocalDate.of(2014, 3, 10));
		map.put(new Version(0, 10, 11), LocalDate.of(2014, 1, 17));
		map.put(new Version(0, 10, 10), LocalDate.of(2013, 11, 6));
		map.put(new Version(0, 10, 9), LocalDate.of(2013, 9, 27));
		map.put(new Version(0, 10, 8), LocalDate.of(2013, 7, 31));
		map.put(new Version(0, 10, 7), LocalDate.of(2013, 4, 10));
		map.put(new Version(0, 10, 6), LocalDate.of(2012, 10, 26));
		map.put(new Version(0, 10, 5), LocalDate.of(2012, 9, 19));
		map.put(new Version(0, 10, 4), LocalDate.of(2012, 6, 9));
		map.put(new Version(0, 10, 3), LocalDate.of(2012, 5, 6));
		map.put(new Version(0, 10, 2), LocalDate.of(2012, 3, 17));
		map.put(new Version(0, 10, 1), LocalDate.of(2012, 3, 17));
		map.put(new Version(0, 10), LocalDate.of(2012, 1, 27));
		map.put(new Version(0, 9, 4), LocalDate.of(2014, 3, 21));
		map.put(new Version(0, 9, 3), LocalDate.of(2013, 9, 23));
		map.put(new Version(0, 9, 2), LocalDate.of(2012, 5, 3));
		map.put(new Version(0, 9, 1), LocalDate.of(2012, 1, 5));
		map.put(new Version(0, 9), LocalDate.of(2011, 12, 11));
		map.put(new Version(0, 8, 15), LocalDate.of(2013, 10, 6));
		map.put(new Version(0, 8, 14), LocalDate.of(2013, 2, 21));
		map.put(new Version(0, 8, 13), LocalDate.of(2013, 2, 18));
		map.put(new Version(0, 8, 12), LocalDate.of(2012, 6, 9));
		map.put(new Version(0, 8, 11), LocalDate.of(2012, 4, 9));
		map.put(new Version(0, 8, 10), LocalDate.of(2012, 1, 13));
		map.put(new Version(0, 8, 9), LocalDate.of(2012, 1, 2));
		map.put(new Version(0, 8, 8), LocalDate.of(2011, 12, 26));
		map.put(new Version(0, 8, 7), LocalDate.of(2011, 11, 21));
		map.put(new Version(0, 8, 6), LocalDate.of(2011, 11, 5));
		map.put(new Version(0, 8, 5), LocalDate.of(2011, 10, 2));
		map.put(new Version(0, 8, 4), LocalDate.of(2011, 9, 22));
		map.put(new Version(0, 8, 3), LocalDate.of(2011, 9, 7));
		map.put(new Version(0, 8, 2), LocalDate.of(2011, 8, 10));
		map.put(new Version(0, 8, 1), LocalDate.of(2011, 7, 28));
		map.put(new Version(0, 8), LocalDate.of(2011, 6, 22));
		map.put(new Version(0, 7, 17), LocalDate.of(2015, 3, 12));
		map.put(new Version(0, 7, 16), LocalDate.of(2013, 10, 6));
		map.put(new Version(0, 7, 15), LocalDate.of(2013, 2, 21));
		map.put(new Version(0, 7, 14), LocalDate.of(2013, 2, 18));
		map.put(new Version(0, 7, 13), LocalDate.of(2012, 6, 9));
		map.put(new Version(0, 7, 12), LocalDate.of(2012, 4, 9));
		map.put(new Version(0, 7, 11), LocalDate.of(2012, 1, 13));
		map.put(new Version(0, 7, 10), LocalDate.of(2012, 1, 2));
		map.put(new Version(0, 7, 9), LocalDate.of(2011, 12, 26));
		map.put(new Version(0, 7, 8), LocalDate.of(2011, 11, 21));
		map.put(new Version(0, 7, 7), LocalDate.of(2011, 11, 5));
		map.put(new Version(0, 7, 6), LocalDate.of(2011, 10, 2));
		map.put(new Version(0, 7, 5), LocalDate.of(2011, 9, 22));
		map.put(new Version(0, 7, 4), LocalDate.of(2011, 9, 7));
		map.put(new Version(0, 7, 3), LocalDate.of(2011, 8, 10));
		map.put(new Version(0, 7, 2), LocalDate.of(2011, 7, 28));
		map.put(new Version(0, 7, 1), LocalDate.of(2011, 6, 23));
		map.put(new Version(0, 7), LocalDate.of(2011, 6, 21));
		map.put(new Version(0, 6, 7), LocalDate.of(2013, 9, 23));
		map.put(new Version(0, 6, 6), LocalDate.of(2012, 6, 9));
		map.put(new Version(0, 6, 5), LocalDate.of(2012, 1, 13));
		map.put(new Version(0, 6, 4), LocalDate.of(2011, 12, 26));
		map.put(new Version(0, 6, 3), LocalDate.of(2011, 4, 26));
		map.put(new Version(0, 6, 2), LocalDate.of(2011, 3, 23));
		map.put(new Version(0, 6, 1), LocalDate.of(2010, 10, 18));
		map.put(new Version(0, 6), LocalDate.of(2010, 6, 15));
		map.put(new Version(0, 5, 15), LocalDate.of(2014, 11, 29));
		map.put(new Version(0, 5, 14), LocalDate.of(2014, 7, 20));
		map.put(new Version(0, 5, 13), LocalDate.of(2013, 9, 25));
		map.put(new Version(0, 5, 12), LocalDate.of(2013, 2, 28));
		map.put(new Version(0, 5, 11), LocalDate.of(2013, 2, 17));
		map.put(new Version(0, 5, 10), LocalDate.of(2012, 6, 9));
		map.put(new Version(0, 5, 9), LocalDate.of(2012, 5, 12));
		map.put(new Version(0, 5, 8), LocalDate.of(2012, 1, 13));
		map.put(new Version(0, 5, 7), LocalDate.of(2011, 12, 26));
		map.put(new Version(0, 5, 6), LocalDate.of(2011, 11, 21));
		map.put(new Version(0, 5, 5), LocalDate.of(2011, 11, 6));
		map.put(new Version(0, 5, 4), LocalDate.of(2011, 3, 17));
		map.put(new Version(0, 5, 3), LocalDate.of(2010, 10, 18));
		map.put(new Version(0, 5, 2), LocalDate.of(2010, 5, 25));
		map.put(new Version(0, 5, 1), LocalDate.of(2010, 3, 2));
		return map;
	}

	/**
	 * @return
	 */
	private static NavigableMap<Integer, LocalDate> buildDateMap() {
		NavigableMap<Integer, LocalDate> map = new TreeMap<>();
		map.put(95171, LocalDate.of(2019, 9, 30));
		map.put(95160, LocalDate.of(2019, 9, 29));
		map.put(95129, LocalDate.of(2019, 9, 28));
		map.put(95111, LocalDate.of(2019, 9, 27));
		map.put(95085, LocalDate.of(2019, 9, 26));
		map.put(95056, LocalDate.of(2019, 9, 25));
		map.put(95032, LocalDate.of(2019, 9, 24));
		map.put(95027, LocalDate.of(2019, 9, 23));
		map.put(95015, LocalDate.of(2019, 9, 22));
		map.put(95004, LocalDate.of(2019, 9, 21));
		map.put(94982, LocalDate.of(2019, 9, 20));
		map.put(94969, LocalDate.of(2019, 9, 19));
		map.put(94960, LocalDate.of(2019, 9, 18));
		map.put(94953, LocalDate.of(2019, 9, 17));
		map.put(94943, LocalDate.of(2019, 9, 16));
		map.put(94911, LocalDate.of(2019, 9, 15));
		map.put(94905, LocalDate.of(2019, 9, 14));
		map.put(94892, LocalDate.of(2019, 9, 13));
		map.put(94887, LocalDate.of(2019, 9, 12));
		map.put(94862, LocalDate.of(2019, 9, 11));
		map.put(94833, LocalDate.of(2019, 9, 10));
		map.put(94821, LocalDate.of(2019, 9, 9));
		map.put(94664, LocalDate.of(2019, 8, 27));
		map.put(94660, LocalDate.of(2019, 8, 26));
		map.put(94652, LocalDate.of(2019, 8, 25));
		map.put(94646, LocalDate.of(2019, 8, 24));
		map.put(94619, LocalDate.of(2019, 8, 23));
		map.put(94609, LocalDate.of(2019, 8, 22));
		map.put(94600, LocalDate.of(2019, 8, 21));
		map.put(94597, LocalDate.of(2019, 8, 20));
		map.put(94576, LocalDate.of(2019, 8, 19));
		map.put(94575, LocalDate.of(2019, 8, 18));
		map.put(94567, LocalDate.of(2019, 8, 17));
		map.put(94566, LocalDate.of(2019, 8, 16));
		map.put(94563, LocalDate.of(2019, 8, 15));
		map.put(94543, LocalDate.of(2019, 8, 14));
		map.put(94530, LocalDate.of(2019, 8, 13));
		map.put(94528, LocalDate.of(2019, 8, 12));
		map.put(94522, LocalDate.of(2019, 8, 12));
		map.put(94500, LocalDate.of(2019, 8, 11));
		map.put(94492, LocalDate.of(2019, 8, 10));
		map.put(94490, LocalDate.of(2019, 8, 9));
		map.put(94489, LocalDate.of(2019, 8, 8));
		map.put(94484, LocalDate.of(2019, 8, 8));
		map.put(94482, LocalDate.of(2019, 8, 7));
		map.put(94481, LocalDate.of(2019, 8, 6));
		map.put(94455, LocalDate.of(2019, 8, 5));
		map.put(94452, LocalDate.of(2019, 8, 4));
		map.put(94436, LocalDate.of(2019, 8, 3));
		map.put(94433, LocalDate.of(2019, 8, 2));
		map.put(94431, LocalDate.of(2019, 8, 1));
		map.put(94423, LocalDate.of(2019, 7, 31));
		map.put(94421, LocalDate.of(2019, 7, 30));
		map.put(94405, LocalDate.of(2019, 7, 29));
		map.put(94396, LocalDate.of(2019, 7, 28));
		map.put(94391, LocalDate.of(2019, 7, 26));
		map.put(94387, LocalDate.of(2019, 7, 25));
		map.put(94383, LocalDate.of(2019, 7, 24));
		map.put(94377, LocalDate.of(2019, 7, 22));
		map.put(94357, LocalDate.of(2019, 7, 21));
		map.put(94345, LocalDate.of(2019, 7, 20));
		map.put(94335, LocalDate.of(2019, 7, 19));
		map.put(94334, LocalDate.of(2019, 7, 18));
		map.put(94324, LocalDate.of(2019, 7, 17));
		map.put(94303, LocalDate.of(2019, 7, 16));
		map.put(94300, LocalDate.of(2019, 7, 15));
		map.put(94284, LocalDate.of(2019, 7, 14));
		map.put(94275, LocalDate.of(2019, 7, 13));
		map.put(94271, LocalDate.of(2019, 7, 12));
		map.put(94270, LocalDate.of(2019, 7, 11));
		map.put(94257, LocalDate.of(2019, 7, 10));
		map.put(94251, LocalDate.of(2019, 7, 9));
		map.put(94212, LocalDate.of(2019, 7, 8));
		map.put(94184, LocalDate.of(2019, 7, 7));
		map.put(94174, LocalDate.of(2019, 7, 6));
		map.put(94167, LocalDate.of(2019, 7, 5));
		map.put(94164, LocalDate.of(2019, 7, 4));
		map.put(94156, LocalDate.of(2019, 7, 3));
		map.put(94150, LocalDate.of(2019, 7, 2));
		map.put(94147, LocalDate.of(2019, 7, 1));
		map.put(94137, LocalDate.of(2019, 6, 30));
		map.put(94129, LocalDate.of(2019, 6, 29));
		map.put(94125, LocalDate.of(2019, 6, 27));
		map.put(94112, LocalDate.of(2019, 6, 26));
		map.put(94099, LocalDate.of(2019, 6, 25));
		map.put(94089, LocalDate.of(2019, 6, 24));
		map.put(94085, LocalDate.of(2019, 6, 23));
		map.put(94077, LocalDate.of(2019, 6, 22));
		map.put(94066, LocalDate.of(2019, 6, 21));
		map.put(94063, LocalDate.of(2019, 6, 20));
		map.put(94061, LocalDate.of(2019, 6, 19));
		map.put(94059, LocalDate.of(2019, 6, 18));
		map.put(94057, LocalDate.of(2019, 6, 17));
		map.put(94054, LocalDate.of(2019, 6, 16));
		map.put(94043, LocalDate.of(2019, 6, 14));
		map.put(94030, LocalDate.of(2019, 6, 13));
		map.put(94017, LocalDate.of(2019, 6, 12));
		map.put(94014, LocalDate.of(2019, 6, 11));
		map.put(94010, LocalDate.of(2019, 6, 10));
		map.put(94008, LocalDate.of(2019, 6, 9));
		map.put(94001, LocalDate.of(2019, 6, 7));
		map.put(93994, LocalDate.of(2019, 6, 5));
		map.put(93986, LocalDate.of(2019, 6, 4));
		map.put(93981, LocalDate.of(2019, 6, 3));
		map.put(93955, LocalDate.of(2019, 6, 2));
		map.put(93953, LocalDate.of(2019, 6, 1));
		map.put(93949, LocalDate.of(2019, 5, 31));
		map.put(93945, LocalDate.of(2019, 5, 30));
		map.put(93944, LocalDate.of(2019, 5, 29));
		map.put(93933, LocalDate.of(2019, 5, 28));
		map.put(93918, LocalDate.of(2019, 5, 27));
		map.put(93913, LocalDate.of(2019, 5, 26));
		map.put(93899, LocalDate.of(2019, 5, 24));
		map.put(93897, LocalDate.of(2019, 5, 23));
		map.put(93894, LocalDate.of(2019, 5, 22));
		map.put(93893, LocalDate.of(2019, 5, 21));
		map.put(93886, LocalDate.of(2019, 5, 20));
		map.put(93885, LocalDate.of(2019, 5, 19));
		map.put(93884, LocalDate.of(2019, 5, 18));
		map.put(93880, LocalDate.of(2019, 5, 17));
		map.put(93871, LocalDate.of(2019, 5, 16));
		map.put(93863, LocalDate.of(2019, 5, 15));
		map.put(93855, LocalDate.of(2019, 5, 14));
		map.put(93851, LocalDate.of(2019, 5, 13));
		map.put(93838, LocalDate.of(2019, 5, 12));
		map.put(93828, LocalDate.of(2019, 5, 11));
		map.put(93825, LocalDate.of(2019, 5, 10));
		map.put(93815, LocalDate.of(2019, 5, 9));
		map.put(93789, LocalDate.of(2019, 5, 8));
		map.put(93784, LocalDate.of(2019, 5, 7));
		map.put(93774, LocalDate.of(2019, 5, 6));
		map.put(93762, LocalDate.of(2019, 5, 5));
		map.put(93755, LocalDate.of(2019, 5, 4));
		map.put(93747, LocalDate.of(2019, 5, 3));
		map.put(93726, LocalDate.of(2019, 5, 2));
		map.put(93264, LocalDate.of(2019, 3, 1));
		map.put(93252, LocalDate.of(2019, 2, 26));
		map.put(93234, LocalDate.of(2019, 2, 25));
		map.put(93230, LocalDate.of(2019, 2, 24));
		map.put(93219, LocalDate.of(2019, 2, 23));
		map.put(93217, LocalDate.of(2019, 2, 22));
		map.put(93214, LocalDate.of(2019, 2, 21));
		map.put(93151, LocalDate.of(2019, 2, 19));
		map.put(93147, LocalDate.of(2019, 2, 18));
		map.put(93139, LocalDate.of(2019, 2, 17));
		map.put(93129, LocalDate.of(2019, 2, 16));
		map.put(93127, LocalDate.of(2019, 2, 14));
		map.put(93125, LocalDate.of(2019, 2, 14));
		map.put(93120, LocalDate.of(2019, 2, 13));
		map.put(93115, LocalDate.of(2019, 2, 12));
		map.put(93114, LocalDate.of(2019, 2, 12));
		map.put(93109, LocalDate.of(2019, 2, 11));
		map.put(93103, LocalDate.of(2019, 2, 10));
		map.put(93094, LocalDate.of(2019, 2, 9));
		map.put(93090, LocalDate.of(2019, 2, 8));
		map.put(93087, LocalDate.of(2019, 2, 7));
		map.put(93083, LocalDate.of(2019, 2, 6));
		map.put(93077, LocalDate.of(2019, 2, 4));
		map.put(93075, LocalDate.of(2019, 2, 3));
		map.put(93069, LocalDate.of(2019, 2, 2));
		map.put(93064, LocalDate.of(2019, 2, 1));
		map.put(93056, LocalDate.of(2019, 1, 31));
		map.put(93044, LocalDate.of(2019, 1, 30));
		map.put(93041, LocalDate.of(2019, 1, 28));
		map.put(93028, LocalDate.of(2019, 1, 27));
		map.put(93022, LocalDate.of(2019, 1, 26));
		map.put(93020, LocalDate.of(2019, 1, 25));
		map.put(93016, LocalDate.of(2019, 1, 24));
		map.put(93005, LocalDate.of(2019, 1, 23));
		map.put(93001, LocalDate.of(2019, 1, 22));
		map.put(92995, LocalDate.of(2019, 1, 21));
		map.put(92989, LocalDate.of(2019, 1, 20));
		map.put(92988, LocalDate.of(2019, 1, 19));
		map.put(92986, LocalDate.of(2019, 1, 18));
		map.put(92982, LocalDate.of(2019, 1, 17));
		map.put(92981, LocalDate.of(2019, 1, 16));
		map.put(92972, LocalDate.of(2019, 1, 15));
		map.put(92966, LocalDate.of(2019, 1, 14));
		map.put(92963, LocalDate.of(2019, 1, 13));
		map.put(92953, LocalDate.of(2019, 1, 12));
		map.put(92944, LocalDate.of(2019, 1, 11));
		map.put(92936, LocalDate.of(2019, 1, 10));
		map.put(92935, LocalDate.of(2019, 1, 9));
		map.put(92932, LocalDate.of(2019, 1, 8));
		map.put(92931, LocalDate.of(2019, 1, 7));
		map.put(92926, LocalDate.of(2019, 1, 6));
		map.put(92924, LocalDate.of(2019, 1, 5));
		map.put(92917, LocalDate.of(2019, 1, 4));
		map.put(92906, LocalDate.of(2019, 1, 3));
		map.put(92899, LocalDate.of(2019, 1, 2));
		// a gap...
		map.put(90884, LocalDate.of(2018, 4, 29));
		// a gap...
		map.put(82966, LocalDate.of(2016, 12, 31));
		map.put(81863, LocalDate.of(2016, 10, 3));
		map.put(80877, LocalDate.of(2016, 6, 29));
		map.put(79056, LocalDate.of(2016, 3, 16));
		map.put(77556, LocalDate.of(2015, 12, 31));
		map.put(72939, LocalDate.of(2015, 6, 15));
		map.put(68810, LocalDate.of(2015, 1, 2));
		map.put(64326, LocalDate.of(2014, 6, 30));
		map.put(59480, LocalDate.of(2014, 1, 2));
		map.put(48409, LocalDate.of(2013, 1, 3));
		map.put(39664, LocalDate.of(2012, 4, 9));
		return map;
	}
}
